#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: books-api
#          uri: http://localhost:8080
#          predicates:
#            - Path=/books/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 2
#                redis-rate-limiter.burstCapacity: 2
#                key-resolver: "#{@ipKeyResolver}"
